const CourseData = [
  {
    id: "1",
    name: "Biology",
    department: "I",
    program: "Biology",
    btn_1Link: "xyz1",
    btn_2Link: "abc1",
    btn_3Link: "qwe1",
    btn_4Link: "cvs1",
  },
  {
    id: "2",
    name: "Chemistry",
    department: "II",
    program: "Chemistry",
    btn_1Link: "xyz2",
    btn_2Link: "abc2",
    btn_3Link: "qwe2",
    btn_4Link: "cvs2",
  },
  {
    id: "3",
    name: "English Grammar",
    department: "III",
    program: "English Grammar",
    btn_1Link: "xyz3",
    btn_2Link: "abc3",
    btn_3Link: "qwe3",
    btn_4Link: "cvs3",
  },
  {
    id: "4",
    name: "Mathamatics",
    department: "VIII",
    program: "Mathamatics",
    btn_1Link: "xyz4",
    btn_2Link: "abc4",
    btn_3Link: "qwe4",
    btn_4Link: "cvs4",
  },
  {
    id: "5",
    name: "Physics",
    department: "IV",
    program: "Physics",
    btn_1Link: "xyz5",
    btn_2Link: "abc5",
    btn_3Link: "qwe5",
    btn_4Link: "cvs5",
  },
  {
    id: "6",
    name: "Social Studies",
    department: "IV",
    program: "Social Studies",
    btn_1Link: "xyz67",
    btn_2Link: "abc67",
    btn_3Link: "qwe67",
    btn_4Link: "cvs67",
  },
  {
    id: "7",
    name: "java",
    department: "V",
    program: "java",
    btn_1Link: "xyz7",
    btn_2Link: "abc7",
    btn_3Link: "qwe7",
    btn_4Link: "cvs7",
  },
  {
    id: "8",
    name: "html",
    department: "VI",
    program: "html",
    btn_1Link: "xyz8",
    btn_2Link: "abc8",
    btn_3Link: "qwe8",
    btn_4Link: "cvs8",
  },
  {
    id: "9",
    name: "css",
    department: "VII",
    program: "css",
    btn_1Link: "xyz9",
    btn_2Link: "abc9",
    btn_3Link: "qwe9",
    btn_4Link: "cvs9",
  },
  {
    id: "10",
    name: "react",
    department: "VIII",
    program: "react",
    btn_1Link: "xyz10",
    btn_2Link: "abc10",
    btn_3Link: "qwe10",
    btn_4Link: "cvs10",
  },
  {
    id: "11",
    name: "nextjs",
    department: " III",
    program: "nextjs",
    btn_1Link: "xyz11",
    btn_2Link: "abc11",
    btn_3Link: "qwe11",
    btn_4Link: "cvs11",
  },
  {
    id: "12",
    name: "jquary",
    department: "II",
    program: "jquary",
    btn_1Link: "xyz12",
    btn_2Link: "abc12",
    btn_3Link: "qwe12",
    btn_4Link: "cvs12",
  },
  {
    id: "13",
    name: "c++",
    department: " IX",
    program: "c++",
    btn_1Link: "xyz13",
    btn_2Link: "abc13",
    btn_3Link: "qwe13",
    btn_4Link: "cvs13",
  },
  {
    id: "14",
    name: "flutter",
    department: "X",
    program: "flutter",
    btn_1Link: "xyz14",
    btn_2Link: "abc14",
    btn_3Link: "qwe14",
    btn_4Link: "cvs14",
  },
  {
    id: "15",
    name: "dart",
    department: "VIII",
    program: "dart",
    btn_1Link: "xyz15",
    btn_2Link: "abc15",
    btn_3Link: "qwe15",
    btn_4Link: "cvs15",
  },
];

export default CourseData;
